import {
  Bell,
  BookOpen,
  CalendarDays,
  Car,
  ChartBar,
  Clock,
  DollarSign,
  Globe,
  Mail,
  Receipt,
  Route,
  Sparkles,
  Timer,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  bell: Bell,
  book: BookOpen,
  calendar: CalendarDays,
  car: Car,
  chart: ChartBar,
  clock: Clock,
  dollar: DollarSign,
  globe: Globe,
  mail: Mail,
  receipt: Receipt,
  route: Route,
  sparkles: Sparkles,
  timer: Timer,
  zap: Zap,
};
