export const ROUTES = {
  APP: {
    TODAY: "/today",
    ACTIVE: "/active",
    MAP: "/day",
    JOBS: "/jobs",
    GAP: "/gap",
    BOOKINGS: "/bookings",
    INVOICES: "/invoices",
    EARNINGS: "/earnings",
    EXPENSES: "/expenses",
    JOURNAL: "/journal",
    REPORTS: "/reports",
    ACCOUNT: "/settings",
    BILLING: "/settings/billing",
    NOTIFICATIONS: "/notifications",
    IMPORT: "/import",
  },
  ONBOARDING: {
    HOME: "/onboarding/home",
    SIGNING_TYPES: "/onboarding/signing-types",
    PLAN: "/onboarding/plan",
    SCANBACK: "/onboarding/scanback",
  },
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgot-password",
  },
  HOME: "/",
};
